#--------------------------------------------------------------------------------------------
#	1.	UTILIZAMOS LA BASE DE DATOS 'NBA'
#--------------------------------------------------------------------------------------------
#	USE <base de datos>
#--------------------------------------------------------------------------------------------
USE nba;
#--------------------------------------------------------------------------------------------
#	2. 	BORRAMOS Y CREAMOS LOS ROLES
#--------------------------------------------------------------------------------------------
#	Rol asociado a NBA y a cada Conferencia (Este, Oeste) y a cada División (Atlántico, Sudeste, Central, Pacífico, Sudoeste y Noroeste)
#--------------------------------------------------------------------------------------------
#	CREATE ROLE <rol>
#--------------------------------------------------------------------------------------------
-- Borramos los roles si existen
DROP ROLE IF EXISTS NBA, CONFERENCIA_ESTE, CONFERENCIA_OESTE, DIVISION_ATLANTICA, DIVISION_SUDESTE,
  DIVISION_CENTRAL, DIVISION_PACIFICO, DIVISION_SUDOESTE, DIVISION_NOROESTE;

-- Creamos los roles
CREATE ROLE NBA;
CREATE ROLE CONFERENCIA_ESTE;
CREATE ROLE CONFERENCIA_OESTE;
CREATE ROLE DIVISION_ATLANTICA;
CREATE ROLE DIVISION_SUDESTE;
CREATE ROLE DIVISION_CENTRAL;
CREATE ROLE DIVISION_PACIFICO;
CREATE ROLE DIVISION_SUDOESTE;
CREATE ROLE DIVISION_NOROESTE;

#--------------------------------------------------------------------------------------------
#	3. BORRAMOS Y CREAMOS LAS VISTAS
#--------------------------------------------------------------------------------------------
#	DROP VIEW IF EXISTS <vista>							CREATE VIEW	<vista>	AS <consulta>
#--------------------------------------------------------------------------------------------
#		Vista General de TODOS los Equipos, otra para TODOS los Jugadores, otra para TODAS las Estadísticas y otra para TODOS los partidos

-- Borrar vistas existentes si existen
DROP VIEW IF EXISTS NBA_EQUIPOS;
DROP VIEW IF EXISTS NBA_JUGADORES;
DROP VIEW IF EXISTS NBA_ESTADISTICAS;
DROP VIEW IF EXISTS NBA_PARTIDOS;

DROP VIEW IF EXISTS CONFERENCIA_ESTE_EQUIPOS;
DROP VIEW IF EXISTS CONFERENCIA_ESTE_JUGADORES;
DROP VIEW IF EXISTS CONFERENCIA_ESTE_ESTADISTICAS;
DROP VIEW IF EXISTS CONFERENCIA_ESTE_PARTIDOS;

DROP VIEW IF EXISTS CONFERENCIA_OESTE_EQUIPOS;
DROP VIEW IF EXISTS CONFERENCIA_OESTE_JUGADORES;
DROP VIEW IF EXISTS CONFERENCIA_OESTE_ESTADISTICAS;
DROP VIEW IF EXISTS CONFERENCIA_OESTE_PARTIDOS;

DROP VIEW IF EXISTS DIVISION_ATLANTICA_EQUIPOS;
DROP VIEW IF EXISTS DIVISION_ATLANTICA_JUGADORES;
DROP VIEW IF EXISTS DIVISION_ATLANTICA_ESTADISTICAS;
DROP VIEW IF EXISTS DIVISION_ATLANTICA_PARTIDOS;

DROP VIEW IF EXISTS DIVISION_SUDESTE_EQUIPOS;
DROP VIEW IF EXISTS DIVISION_SUDESTE_JUGADORES;
DROP VIEW IF EXISTS DIVISION_SUDESTE_ESTADISTICAS;
DROP VIEW IF EXISTS DIVISION_SUDESTE_PARTIDOS;

DROP VIEW IF EXISTS DIVISION_CENTRAL_EQUIPOS;
DROP VIEW IF EXISTS DIVISION_CENTRAL_JUGADORES;
DROP VIEW IF EXISTS DIVISION_CENTRAL_ESTADISTICAS;
DROP VIEW IF EXISTS DIVISION_CENTRAL_PARTIDOS;

DROP VIEW IF EXISTS DIVISION_PACIFICO_EQUIPOS;
DROP VIEW IF EXISTS DIVISION_PACIFICO_JUGADORES;
DROP VIEW IF EXISTS DIVISION_PACIFICO_ESTADISTICAS;
DROP VIEW IF EXISTS DIVISION_PACIFICO_PARTIDOS;

DROP VIEW IF EXISTS DIVISION_SUDOESTE_EQUIPOS;
DROP VIEW IF EXISTS DIVISION_SUDOESTE_JUGADORES;
DROP VIEW IF EXISTS DIVISION_SUDOESTE_ESTADISTICAS;
DROP VIEW IF EXISTS DIVISION_SUDOESTE_PARTIDOS;

DROP VIEW IF EXISTS DIVISION_NOROESTE_EQUIPOS;
DROP VIEW IF EXISTS DIVISION_NOROESTE_JUGADORES;
DROP VIEW IF EXISTS DIVISION_NOROESTE_ESTADISTICAS;
DROP VIEW IF EXISTS DIVISION_NOROESTE_PARTIDOS;


-- Crear vistas generales
CREATE VIEW NBA_EQUIPOS AS SELECT * FROM NBA.equipos;
CREATE VIEW NBA_JUGADORES AS SELECT * FROM NBA.jugadores;
CREATE VIEW NBA_ESTADISTICAS AS SELECT * FROM NBA.estadisticas;
CREATE VIEW NBA_PARTIDOS AS SELECT * FROM NBA.partidos;

-- Crear vistas sobre la Conferencia Este
CREATE VIEW CONFERENCIA_ESTE_EQUIPOS AS SELECT * FROM NBA_EQUIPOS WHERE Conferencia = 'East';
CREATE VIEW CONFERENCIA_ESTE_JUGADORES AS SELECT * FROM NBA_JUGADORES WHERE nombre_equipo IN (SELECT nombre FROM CONFERENCIA_ESTE_EQUIPOS);
CREATE VIEW CONFERENCIA_ESTE_ESTADISTICAS AS SELECT * FROM NBA_ESTADISTICAS WHERE jugador IN (SELECT codigo FROM CONFERENCIA_ESTE_JUGADORES);
CREATE VIEW CONFERENCIA_ESTE_PARTIDOS AS SELECT * FROM NBA_PARTIDOS WHERE equipo_local IN (SELECT nombre FROM CONFERENCIA_ESTE_EQUIPOS) OR equipo_visitante IN(SELECT nombre FROM CONFERENCIA_ESTE_EQUIPOS);

-- Crear vistas sobre la Conferencia Oeste
CREATE VIEW CONFERENCIA_OESTE_EQUIPOS AS SELECT * FROM NBA_EQUIPOS WHERE Conferencia = 'West';
CREATE VIEW CONFERENCIA_OESTE_JUGADORES AS SELECT * FROM NBA_JUGADORES WHERE nombre_equipo IN (SELECT nombre FROM CONFERENCIA_OESTE_EQUIPOS);
CREATE VIEW CONFERENCIA_OESTE_ESTADISTICAS AS SELECT * FROM NBA_ESTADISTICAS WHERE jugador IN (SELECT codigo FROM CONFERENCIA_OESTE_JUGADORES);
CREATE VIEW CONFERENCIA_OESTE_PARTIDOS AS SELECT * FROM NBA_PARTIDOS WHERE equipo_local IN (SELECT nombre FROM CONFERENCIA_OESTE_EQUIPOS) OR equipo_visitante IN (SELECT nombre FROM CONFERENCIA_OESTE_EQUIPOS);

-- Crear vistas sobre la División Atlántica
CREATE VIEW DIVISION_ATLANTICA_EQUIPOS AS SELECT * FROM NBA_EQUIPOS WHERE Division = 'Atlantica';
CREATE VIEW DIVISION_ATLANTICA_JUGADORES AS SELECT * FROM NBA_JUGADORES WHERE nombre_equipo IN (SELECT nombre FROM DIVISION_ATLANTICA_EQUIPOS);
CREATE VIEW DIVISION_ATLANTICA_ESTADISTICAS AS SELECT * FROM NBA_ESTADISTICAS WHERE jugador IN (SELECT codigo FROM DIVISION_ATLANTICA_JUGADORES);
CREATE VIEW DIVISION_ATLANTICA_PARTIDOS AS SELECT * FROM NBA_PARTIDOS WHERE equipo_local IN (SELECT nombre FROM DIVISION_ATLANTICA_EQUIPOS) OR equipo_visitante IN (SELECT nombre FROM DIVISION_ATLANTICA_EQUIPOS);

-- Crear vistas sobre la División Sudeste
CREATE VIEW DIVISION_SUDESTE_EQUIPOS AS SELECT * FROM NBA_EQUIPOS WHERE Division = 'SouthEast';
CREATE VIEW DIVISION_SUDESTE_JUGADORES AS SELECT * FROM NBA_JUGADORES WHERE nombre_equipo IN (SELECT nombre FROM DIVISION_SUDESTE_EQUIPOS);
CREATE VIEW DIVISION_SUDESTE_ESTADISTICAS AS SELECT * FROM NBA_ESTADISTICAS WHERE jugador IN (SELECT codigo FROM DIVISION_SUDESTE_JUGADORES);
CREATE VIEW DIVISION_SUDESTE_PARTIDOS AS SELECT * FROM NBA_PARTIDOS WHERE equipo_local IN (SELECT nombre FROM DIVISION_SUDESTE_EQUIPOS) OR equipo_visitante IN (SELECT nombre FROM DIVISION_SUDESTE_EQUIPOS);

-- Crear vistas sobre la División Central
CREATE VIEW DIVISION_CENTRAL_EQUIPOS AS SELECT * FROM NBA_EQUIPOS WHERE Division = 'Central';
CREATE VIEW DIVISION_CENTRAL_JUGADORES AS SELECT * FROM NBA_JUGADORES WHERE nombre_equipo IN (SELECT nombre FROM DIVISION_CENTRAL_EQUIPOS);
CREATE VIEW DIVISION_CENTRAL_ESTADISTICAS AS SELECT * FROM NBA_ESTADISTICAS WHERE jugador IN (SELECT codigo FROM DIVISION_CENTRAL_JUGADORES);
CREATE VIEW DIVISION_CENTRAL_PARTIDOS AS SELECT * FROM NBA_PARTIDOS WHERE equipo_local IN (SELECT nombre FROM DIVISION_CENTRAL_EQUIPOS) OR equipo_visitante IN (SELECT nombre FROM DIVISION_CENTRAL_EQUIPOS);

-- Crear vistas sobre la División Pacífico
CREATE VIEW DIVISION_PACIFICO_EQUIPOS AS SELECT * FROM NBA_EQUIPOS WHERE Division = 'Pacific';
CREATE VIEW DIVISION_PACIFICO_JUGADORES AS SELECT * FROM NBA_JUGADORES WHERE nombre_equipo IN (SELECT nombre FROM DIVISION_PACIFICO_EQUIPOS);
CREATE VIEW DIVISION_PACIFICO_ESTADISTICAS AS SELECT * FROM NBA_ESTADISTICAS WHERE jugador IN (SELECT codigo FROM DIVISION_PACIFICO_JUGADORES);
CREATE VIEW DIVISION_PACIFICO_PARTIDOS AS SELECT * FROM NBA_PARTIDOS WHERE equipo_local IN (SELECT nombre FROM DIVISION_PACIFICO_EQUIPOS) OR equipo_visitante IN (SELECT nombre FROM DIVISION_PACIFICO_EQUIPOS);

-- Crear vistas sobre la División Sudoeste
CREATE VIEW DIVISION_SUDOESTE_EQUIPOS AS SELECT * FROM NBA_EQUIPOS WHERE Division = 'SouthWest';
CREATE VIEW DIVISION_SUDOESTE_JUGADORES AS SELECT * FROM NBA_JUGADORES WHERE nombre_equipo IN (SELECT nombre FROM DIVISION_SUDOESTE_EQUIPOS);
CREATE VIEW DIVISION_SUDOESTE_ESTADISTICAS AS SELECT * FROM NBA_ESTADISTICAS WHERE jugador IN (SELECT codigo FROM DIVISION_SUDOESTE_JUGADORES);
CREATE VIEW DIVISION_SUDOESTE_PARTIDOS AS SELECT * FROM NBA_PARTIDOS WHERE equipo_local IN (SELECT nombre FROM DIVISION_SUDOESTE_EQUIPOS) OR equipo_visitante IN (SELECT nombre FROM DIVISION_SUDOESTE_EQUIPOS);

-- Crear vistas sobre la División Noroeste
CREATE VIEW DIVISION_NOROESTE_EQUIPOS AS SELECT * FROM NBA_EQUIPOS WHERE Division = 'NorthWest';
CREATE VIEW DIVISION_NOROESTE_JUGADORES AS SELECT * FROM NBA_JUGADORES WHERE nombre_equipo IN (SELECT nombre FROM DIVISION_NOROESTE_EQUIPOS);
CREATE VIEW DIVISION_NOROESTE_ESTADISTICAS AS SELECT * FROM NBA_ESTADISTICAS WHERE jugador IN (SELECT codigo FROM DIVISION_NOROESTE_JUGADORES);
CREATE VIEW DIVISION_NOROESTE_PARTIDOS AS SELECT * FROM NBA_PARTIDOS WHERE equipo_local IN (SELECT nombre FROM DIVISION_NOROESTE_EQUIPOS) OR equipo_visitante IN (SELECT nombre FROM DIVISION_NOROESTE_EQUIPOS);

#--------------------------------------------------------------------------------------------
#	4. ASIGNAMOS PRIVILEGIOS (O PERMISOS) A LOS ROLES
#--------------------------------------------------------------------------------------------
#	GRANT <privilegio>	ON <vista>	TO 	<rol>
#--------------------------------------------------------------------------------------------

-- Asignar todos los permisos al rol asociado a TODOS los datos
GRANT ALL PRIVILEGES ON NBA_EQUIPOS TO NBA;
GRANT ALL PRIVILEGES ON NBA_JUGADORES TO NBA;
GRANT ALL PRIVILEGES ON NBA_ESTADISTICAS TO NBA;
GRANT ALL PRIVILEGES ON NBA_PARTIDOS TO NBA;

-- Asignar todos los permisos al rol asociado a la Conferencia ESTE
GRANT ALL PRIVILEGES ON CONFERENCIA_ESTE_EQUIPOS TO CONFERENCIA_ESTE;
GRANT ALL PRIVILEGES ON CONFERENCIA_ESTE_JUGADORES TO CONFERENCIA_ESTE;
GRANT ALL PRIVILEGES ON CONFERENCIA_ESTE_ESTADISTICAS TO CONFERENCIA_ESTE;
GRANT ALL PRIVILEGES ON CONFERENCIA_ESTE_PARTIDOS TO CONFERENCIA_ESTE;

-- Asignar todos los permisos al rol asociado a la Conferencia OESTE
GRANT ALL PRIVILEGES ON CONFERENCIA_OESTE_EQUIPOS TO CONFERENCIA_OESTE;
GRANT ALL PRIVILEGES ON CONFERENCIA_OESTE_JUGADORES TO CONFERENCIA_OESTE;
GRANT ALL PRIVILEGES ON CONFERENCIA_OESTE_ESTADISTICAS TO CONFERENCIA_OESTE;
GRANT ALL PRIVILEGES ON CONFERENCIA_OESTE_PARTIDOS TO CONFERENCIA_OESTE;

-- Asignar todos los permisos al rol asociado a la División Atlántica
GRANT ALL PRIVILEGES ON DIVISION_ATLANTICA_EQUIPOS TO DIVISION_ATLANTICA;
GRANT ALL PRIVILEGES ON DIVISION_ATLANTICA_JUGADORES TO DIVISION_ATLANTICA;
GRANT ALL PRIVILEGES ON DIVISION_ATLANTICA_ESTADISTICAS TO DIVISION_ATLANTICA;
GRANT ALL PRIVILEGES ON DIVISION_ATLANTICA_PARTIDOS TO DIVISION_ATLANTICA;

-- Asignar todos los permisos al rol asociado a la División Sudeste
GRANT ALL PRIVILEGES ON DIVISION_SUDESTE_EQUIPOS TO DIVISION_SUDESTE;
GRANT ALL PRIVILEGES ON DIVISION_SUDESTE_JUGADORES TO DIVISION_SUDESTE;
GRANT ALL PRIVILEGES ON DIVISION_SUDESTE_ESTADISTICAS TO DIVISION_SUDESTE;
GRANT ALL PRIVILEGES ON DIVISION_SUDESTE_PARTIDOS TO DIVISION_SUDESTE;

-- Asignar todos los permisos al rol asociado a la División Central
GRANT ALL PRIVILEGES ON DIVISION_CENTRAL_EQUIPOS TO DIVISION_CENTRAL;
GRANT ALL PRIVILEGES ON DIVISION_CENTRAL_JUGADORES TO DIVISION_CENTRAL;
GRANT ALL PRIVILEGES ON DIVISION_CENTRAL_ESTADISTICAS TO DIVISION_CENTRAL;
GRANT ALL PRIVILEGES ON DIVISION_CENTRAL_PARTIDOS TO DIVISION_CENTRAL;

-- Asignar todos los permisos al rol asociado a la División Pacífico
GRANT ALL PRIVILEGES ON DIVISION_PACIFICO_EQUIPOS TO DIVISION_PACIFICO;
GRANT ALL PRIVILEGES ON DIVISION_PACIFICO_JUGADORES TO DIVISION_PACIFICO;
GRANT ALL PRIVILEGES ON DIVISION_PACIFICO_ESTADISTICAS TO DIVISION_PACIFICO;
GRANT ALL PRIVILEGES ON DIVISION_PACIFICO_PARTIDOS TO DIVISION_PACIFICO;

-- Asignar todos los permisos al rol asociado a la División Sudoeste
GRANT ALL PRIVILEGES ON DIVISION_SUDOESTE_EQUIPOS TO DIVISION_SUDOESTE;
GRANT ALL PRIVILEGES ON DIVISION_SUDOESTE_JUGADORES TO DIVISION_SUDOESTE;
GRANT ALL PRIVILEGES ON DIVISION_SUDOESTE_ESTADISTICAS TO DIVISION_SUDOESTE;
GRANT ALL PRIVILEGES ON DIVISION_SUDOESTE_PARTIDOS TO DIVISION_SUDOESTE;

-- Asignar todos los permisos al rol asociado a la División Noroeste
GRANT ALL PRIVILEGES ON DIVISION_NOROESTE_EQUIPOS TO DIVISION_NOROESTE;
GRANT ALL PRIVILEGES ON DIVISION_NOROESTE_JUGADORES TO DIVISION_NOROESTE;
GRANT ALL PRIVILEGES ON DIVISION_NOROESTE_ESTADISTICAS TO DIVISION_NOROESTE;
GRANT ALL PRIVILEGES ON DIVISION_NOROESTE_PARTIDOS TO DIVISION_NOROESTE;


#--------------------------------------------------------------------------------------------
#	5. 	BORRAMOS Y CREAMOS LOS USUARIOS, ASIGNÁNDOLES POR DEFECTO SU ROL ASOCIADO
#	Los usuarios serán creados todos con la misma clave 'abc'
#--------------------------------------------------------------------------------------------
#	CREATE USER <usuario>	IDENTIFIED BY <clave>	DEFAULT ROLE <rol>
#--------------------------------------------------------------------------------------------
#	Fulgencio y Fulgencia
#	Guillermino y Guillermina
#	Pancracio y Pancracia
#	Filomeno y Filomena
#	Anaximandro y Anaximandra
#	Romino y Romina
#	Agapito y Agapita
#	Apolonio y Apolonia
#	Luzdivino y Luzdivina
#--------------------------------------------------------------------------------------------
 -- Borramos los usuarios si existen
DROP USER IF EXISTS 'Fulgencio', 'Fulgencia', 'Guillermino', 'Guillermina', 'Pancracio', 'Pancracia',
  'Filomeno', 'Filomena', 'Anaximandro', 'Anaximandra', 'Romino', 'Romina', 'Agapito', 'Agapita',
  'Apolonio', 'Apolonia', 'Luzdivino', 'Luzdivina';

-- Creamos los usuarios y les asignamos los roles por defecto
CREATE USER 'Fulgencio' IDENTIFIED BY 'abc' , 'Fulgencia' IDENTIFIED BY 'abc';
GRANT NBA TO 'Fulgencio', 'Fulgencia';
SET DEFAULT ROLE NBA FOR 'Fulgencio';
SET DEFAULT ROLE NBA FOR 'Fulgencia';

CREATE USER 'Guillermino' IDENTIFIED BY 'abc', 'Guillermina' IDENTIFIED BY 'abc';
GRANT CONFERENCIA_ESTE TO 'Guillermino', 'Guillermina';
SET DEFAULT ROLE CONFERENCIA_ESTE FOR 'Guillermino';
SET DEFAULT ROLE CONFERENCIA_ESTE FOR 'Guillermina';

CREATE USER 'Pancracio' IDENTIFIED BY 'abc', 'Pancracia'  IDENTIFIED BY 'abc';
GRANT CONFERENCIA_OESTE TO 'Pancracio', 'Pancracia';
SET DEFAULT ROLE CONFERENCIA_OESTE FOR 'Pancracio';
SET DEFAULT ROLE CONFERENCIA_OESTE FOR 'Pancracia';

CREATE USER 'Filomeno' IDENTIFIED BY 'abc', 'Filomena' IDENTIFIED BY 'abc';
GRANT DIVISION_ATLANTICA TO 'Filomeno', 'Filomena';
SET DEFAULT ROLE DIVISION_ATLANTICA FOR 'Filomeno';
SET DEFAULT ROLE DIVISION_ATLANTICA FOR 'Filomena';


CREATE USER 'Anaximandro' IDENTIFIED BY 'abc', 'Anaximandra' IDENTIFIED BY 'abc';
GRANT DIVISION_SUDESTE TO 'Anaximandro', 'Anaximandra';
SET DEFAULT ROLE DIVISION_SUDESTE FOR 'Anaximandro';
SET DEFAULT ROLE DIVISION_SUDESTE FOR 'Anaximandra';

CREATE USER 'Romino', 'Romina' IDENTIFIED BY 'abc';
GRANT DIVISION_CENTRAL TO 'Romino', 'Romina';
SET DEFAULT ROLE DIVISION_CENTRAL FOR 'Romino';
SET DEFAULT ROLE DIVISION_CENTRAL FOR 'Romina';

CREATE USER 'Agapito' IDENTIFIED BY 'abc', 'Agapita' IDENTIFIED BY 'abc';
GRANT DIVISION_PACIFICO TO 'Agapito', 'Agapita';
SET DEFAULT ROLE DIVISION_PACIFICO FOR 'Agapito';
SET DEFAULT ROLE DIVISION_PACIFICO FOR 'Agapita';


CREATE USER 'Apolonio' IDENTIFIED BY 'abc', 'Apolonia' IDENTIFIED BY 'abc';
GRANT DIVISION_SUDOESTE TO 'Apolonio', 'Apolonia';
SET DEFAULT ROLE DIVISION_SUDOESTE FOR 'Apolonio';
SET DEFAULT ROLE DIVISION_SUDOESTE FOR 'Apolonia';


CREATE USER 'Luzdivino' IDENTIFIED BY 'abc', 'Luzdivina' IDENTIFIED BY 'abc';
GRANT DIVISION_NOROESTE TO 'Luzdivino', 'Luzdivina';
SET DEFAULT ROLE DIVISION_NOROESTE FOR 'Luzdivino';
SET DEFAULT ROLE DIVISION_NOROESTE FOR 'Luzdivina';

#--------------------------------------------------------------------------------------------
#	6. REFRESCA LOS PRIVILEGIOS
#--------------------------------------------------------------------------------------------
#	FLUSH PRIVILEGES;
#--------------------------------------------------------------------------------------------
FLUSH PRIVILEGES;
